INSERT INTO CATALOG(PRODUCT_NAME, STOCK, UNIT_PRICE) VALUES('TV', 100, 1000);
INSERT INTO CATALOG(PRODUCT_NAME, STOCK, UNIT_PRICE) VALUES('Computer', 120, 1500);
INSERT INTO CATALOG(PRODUCT_NAME, STOCK, UNIT_PRICE) VALUES('Phone', 140, 2000);