services:
  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"

  api-gateway-service:
    build: ./api-gateway-service
    ports:
      - "8000:8000"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service

  user-service:
    build: ./user-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SERVER_PORT=0
    depends_on:
      - discovery-service

  catalog-service:
    build: ./catalog-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SERVER_PORT=0
    depends_on:
      - discovery-service

  order-service:
    build: ./order-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SERVER_PORT=0
    depends_on:
      - discovery-service