server:
  port: 0

spring:
  application:
    name: user-service

  output:
    ansi:
      enabled: always

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update

  security:
    user:
      name: user
      password: $2a$10$mWTLVTAHDILi3zGbd0EUU.Mew49uPJMUUh.5yUg4DnlVKWlcp5bWq

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # bootstrap 의존성을 제거하지 않으면 오류가 발생
  # bootstrap.yml 대신에 spring.config.import 사용
  config:
    import: "optional:configserver:http://localhost:8888"
  # spring.application.name 이름으로 파일을 찾기 때문에 ecommerce 명시
  cloud:
    config:
      name: ecommerce

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#token:
#  secret: e-commerce user-service user-token
#  expiration-time: 86400000

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          - beans
          - info
          - busrefresh