server:
  port: 8000

spring:
  application:
    name: api-gateway-service

  # Gateway, not gateway-MVC, to be dependent on Gateway, the server runs to Netty, not Tomcat
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true

      # Write in YML like this or write like filterConfig.class
      routes:
        - id: first-service
          uri: http://localhost:8081/
          predicates:
            - Path=/test/a, /test/b
          filters:
            - AddRequestHeader=user-request, user-request-header123
            - AddResponseHeader=user-response, user-response-header123
            - name: CustomFilter

        - id: second-service
          uri: http://localhost:8081/
          predicates:
            - Path=/test/c
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Spring Cloud Gateway Logging Filter
                preLogger: true
                postLogger: true
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka